user:
  maximum_name: 50
  maximum_email: 255
  minimum_password: 6
  resetpw: 2
  resize_to_limit: [500,500]
helper:
  size: 80
index_html:
  size: 50
micropost:
  maximum: 140
  micropost_html_size: 50
userinfo:
  size: 50
